repos:
  - repo: local
    hooks:
      - id: statix
        name: Lint Nix files
        entry: statix check .
        pass_filenames: false
        language: system
        files: ^.*\.nix$
      - id: deadnix
        name: Scan Nix files for dead code
        entry: deadnix --fail --no-lambda-arg --no-lambda-pattern-names
        language: system
        files: ^.*\.nix$
      - id: nixpkgs-fmt
        name: Format Nix files
        entry: nixpkgs-fmt
        language: system
        files: ^.*\.nix$
