name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Check flake and packages
        run: |
          nix flake check

      - name: Check formats
        run: |
          nix develop .#ci-check-format --command bash -c "pre-commit run --all-files"

      - name: Check versions
        run: |
          nix develop .#ci-check-versions --command bash -c "./tools/check-versions.sh"
