name: Update

on:
  schedule:
    - cron: "15 14 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.M15A_GITHUB_PAT }}
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Update flake
        run: |
          nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: auto flake update"
          branch: ${{ github.head_ref }}
